core:
  host: "localhost"
  port: 9876

  paths:
    base:
      dir: "pantalone"
    logs:
      dir: "logs"
    db:
      dir: "db"
      name: "pantalone.db"
    temp:
      dir: "temp"
    clean_docs:
      dir: "docs"
