core:
  host: "localhost"
  port: 9876

  paths:
    base:
      dir: "pantalone"
    logs:
      dir: "logs"
    db:
      dir: "db"
      name: "pantalone.db"
    rag:
      dir: "rag"
      raw:
        dir: "raw"
      processed:
        dir: "processed"
      inverted_index:
        dir: "inverted_index"
      vector_db:
        dir: "vector_db"
    temp:
      dir: "temp"
